---
- name: Create uptime-kuma data volume
  community.docker.docker_volume:
    name: uptime-kuma_data

- name: Ensure louislam/uptime-kuma image is pulled
  community.docker.docker_image:
    name: docker.io/louislam/uptime-kuma
    source: pull
    force_source: yes
  register: pulled

- name: Remove uptime-kuma container
  community.docker.docker_container:
    name: uptime-kuma
    state: absent
  when: pulled.changed

- name: Get infos on uptime-kuma container
  community.docker.docker_container_info:
    name: uptime-kuma
  register: result

- name: Create uptime-kuma container
  community.docker.docker_container:
    image: docker.io/louislam/uptime-kuma
    mounts:
     - source: uptime-kuma_data
       target: /app/data
    name: uptime-kuma
    networks:
     - name: app-network
    restart_policy: unless-stopped
    state: started
  when:
    (pulled.changed or result.exists == false) and app_uptime_kuma_cloudflared_token == ""

- name: Create uptime-kuma container with cf reverse proxy
  community.docker.docker_container:
    image: docker.io/louislam/uptime-kuma
    mounts:
     - source: uptime-kuma_data
       target: /app/data
    name: uptime-kuma
    env:
      UPTIME_KUMA_CLOUDFLARED_TOKEN: "{{ app_uptime_kuma_cloudflared_token }}"
    restart_policy: unless-stopped
    state: started
  when:
    (pulled.changed or result.exists == false) and app_uptime_kuma_cloudflared_token != ""
