---
- name: Create uptime-kuma data volume
  community.docker.docker_volume:
    name: "{{ app_uptime_kuma_docker_volume }}"

- name: Ensure uptime-kuma image is pulled
  community.docker.docker_image:
    name: "{{ app_uptime_kuma_docker_image }}"
    source: pull
    force_source: yes
  register: pulled

- name: Remove uptime-kuma container
  community.docker.docker_container:
    name: "{{ app_uptime_kuma_docker_container }}"
    state: absent
  when: pulled.changed

- name: Get infos on uptime-kuma container
  community.docker.docker_container_info:
    name: "{{ app_uptime_kuma_docker_container }}"
  register: result

- name: Create uptime-kuma container
  community.docker.docker_container:
    image: "{{ app_uptime_kuma_docker_image }}"
    mounts:
     - source: "{{ app_uptime_kuma_docker_volume }}"
       target: /app/data
    name: "{{ app_uptime_kuma_docker_container }}"
    networks:
     - name: "{{ app_uptime_kuma_docker_network }}"
    restart_policy: unless-stopped
    state: started
  when:
    (pulled.changed or result.exists == false) and app_uptime_kuma_cloudflared_token == ""

- name: Create uptime-kuma container with cf reverse proxy
  community.docker.docker_container:
    image: "{{ app_uptime_kuma_docker_image }}"
    mounts:
     - source: "{{ app_uptime_kuma_docker_volume }}"
       target: /app/data
    name: "{{ app_uptime_kuma_docker_container }}"
    env:
      UPTIME_KUMA_CLOUDFLARED_TOKEN: "{{ app_uptime_kuma_cloudflared_token }}"
    restart_policy: unless-stopped
    state: started
  when:
    (pulled.changed or result.exists == false) and app_uptime_kuma_cloudflared_token != ""
